name: Deploy to Railway Dev Environment

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Migrate database
        run: sequelize-cli db:migrate

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}
# RAILWAY_DEV_TOKEN: b291d159-afe3-4b4f-af59-8c71523a1a4d